// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpfyxehlumfgsfssfvbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZnl4ZWhsdW1mZ3Nmc3NmdmJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzU1MDEsImV4cCI6MjA2Nzk1MTUwMX0.7bdPMCIwuP5tGx5q9vG713qi_ol3XN3sIC4sZar2D54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});